### ISSUE TITLE
bug(macos): shortcut discrepancy

### ISSUE THREAD

**Issue by daiyam** [ranyitz/vscode-search-presets#3]
Hi,

Thank you for the extension. 

There is a small *bug* due to a discrepancy between the code and doc about the shortcut on macos.

https://github.com/ranyitz/vscode-search-presets/blob/c4ac5780356d30cee71ca3301b6217e9101f1d86/package.json#L32

https://github.com/ranyitz/vscode-search-presets/blob/c4ac5780356d30cee71ca3301b6217e9101f1d86/README.md?plain=1#L24

**Comment by ranyitz** [comment]
Thanks @daiyam,
you're absolutely right, please review this PR to let me know what you think - https://github.com/ranyitz/vscode-search-presets/pull/4

**Comment by daiyam** [comment]
OH! I've just realized that `Shift+Alt+F` is overriding the default shortcut for `editor.action.formatDocument` for both macOS and Windows...

**Comment by ranyitz** [comment]
First, this is just the default, you can change it to whatever you see fit.
I personally use format on save, so I don't need to manually trigger formatting via the shortcut

**Comment by daiyam** [comment]
> First, this is just the default, you can change it to whatever you see fit.

Yep, I've changed it. But it's just kinda weird. That's all.

**Comment by ranyitz** [comment]
Out of interest, what shortcut did you change it to?

**Comment by daiyam** [comment]
There is quite a lot on the `f` key, so I went with `ctrl+shift+cmd+f`.

**Comment by daiyam** [comment]
I've finally switch the `cmd+e cmd+f` which is easier to do...
